#!/usr/bin/python3
import os
import sys
import json
import asyncio
import datetime
from playwright.async_api import async_playwright

# --- CONFIGURAZIONE INTERNA ---
CONFIG_FILE = "config_cookie.json"

def carica_configurazione():
    """Carica le credenziali e i parametri dal file JSON esterno."""
    if not os.path.exists(CONFIG_FILE):
        print(f"ERRORE CRITICO: Il file di configurazione '{CONFIG_FILE}' non esiste.")
        print("Crea il file JSON con i campi richiesti.")
        sys.exit(1)
        
    try:
        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            config = json.load(f)
            
        # Verifica la presenza di tutti i campi necessari
        campi_richiesti = ["username", "password", "base_url", "cookie_file", "browserless_url"]
        for campo in campi_richiesti:
            if campo not in config or not config[campo]:
                print(f"ERRORE CRITICO: Il campo '{campo}' manca o è vuoto in {CONFIG_FILE}.")
                sys.exit(1)
                
        return config
    except json.JSONDecodeError:
        print(f"ERRORE CRITICO: Il file '{CONFIG_FILE}' non è un JSON valido. Controlla la sintassi.")
        sys.exit(1)

def salva_cookie_formato_netscape(cookies, output_file):
    """Salva i cookie nel formato standard Netscape leggibile dagli altri script."""
    try:
        with open(output_file, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by rinnova_cookie.py. Do not edit.\n\n")
            
            for c in cookies:
                # Gestione scadenza (se assente, impostiamo 1 anno nel futuro)
                expires = int(c.get("expires", -1))
                if expires == -1:
                    expires = int((datetime.datetime.now() + datetime.timedelta(days=365)).timestamp())
                
                domain = c["domain"]
                flag = "TRUE" if domain.startswith(".") else "FALSE"
                path = c["path"]
                secure = "TRUE" if c["secure"] else "FALSE"
                name = c["name"]
                value = c["value"]
                
                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
        
        os.chmod(output_file, 0o777)
        print(f"Cookie salvati con successo in: {output_file}")
    except Exception as e:
        print(f"Errore nel salvataggio del file cookie: {e}")

async def rinnova_cookie():
    config = carica_configurazione()
    
    username = config["username"]
    password = config["password"]
    base_url = config["base_url"]
    cookie_file = config["cookie_file"]
    browserless_url = config["browserless_url"]
    
    print(f"Connessione a Browserless: {browserless_url}...")
    
    async with async_playwright() as p:
        try:
            # Connessione al container Browserless tramite WebSocket
            browser = await p.chromium.connect_over_cdp(browserless_url)
            context = await browser.new_context(
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            )
            page = await context.new_page()
            
            # 1. Navigazione verso la pagina di login (Modificato wait_until)
            url_login = f"{base_url.rstrip('/')}/login"
            print(f"Navigazione su {url_login}...")
            
            # Usiamo 'domcontentloaded' per non rimanere appesi alle connessioni pubblicitarie di background
            await page.goto(url_login, timeout=45000, wait_until="domcontentloaded")
            
            # 2. Compilazione Form di Login (Aggiunto wait_for_selector)
            print("Attesa visibilità campi credenziali...")
            # Sostituisci i selettori se il sito usa ID o classi diverse (es: '#username' o '#password')
            await page.wait_for_selector('input[name="username"]', timeout=15000)
            
            print("Inserimento credenziali...")
            await page.fill('input[name="username"]', username)
            await page.fill('input[name="password"]', password)
            
            # 3. Invio della richiesta
            print("Invio form di login...")
            # Sostituisci con il selettore corretto del bottone di submit (es. 'button[type="submit"]')
            await page.click('button[type="submit"]')
            
            # Aspettiamo che la pagina post-login carichi la struttura base
            print("Attesa reindirizzamento post-login...")
            await page.wait_for_load_state("domcontentloaded", timeout=20000)
            
            # Piccolo stop di sicurezza di 3 secondi per dare tempo al server di rilasciare i cookie
            await page.wait_for_timeout(30000) # 3 secondi di tolleranza
            
            # Verifichiamo se siamo entrati controllando i cookie generati
            cookies = await context.cookies()
            
            if any(c['name'] for c in cookies if 'session' in c['name'].lower() or 'auth' in c['name'].lower() or 'user' in c['name'].lower()):
                print("Login effettuato con successo. Estrazione cookie in corso...")
                salva_cookie_formato_netscape(cookies, cookie_file)
            else:
                print("ATTENZIONE: Login completato ma nessun cookie di sessione rilevato. Verificare i selettori CSS o le credenziali.")
                salva_cookie_formato_netscape(cookies, cookie_file)
                
            await browser.close()
            
        except Exception as e:
            print(f"ERRORE CRITICO durante l'esecuzione di Playwright: {e}")
            sys.exit(1)

if __name__ == "__main__":
    # Esecuzione del ciclo asincrono richiesto da Playwright
    asyncio.run(rinnova_cookie())
